version: "3.6"
services:
  web:
    environment:
      - ENVIRONMENT=test
      - DB_HOST=db
      - DB_NAME=desparking
      - DB_USER=root
      - DB_PASSWD=root
      - MAPBOX_TOKEN=pk.eyJ1IjoiaGhlbnJ5NDQzIiwiYSI6ImNtaHZ4bnJzOTAwdWQyanI3Z2o5c2JtZmgifQ.9UujI0W5H9tCBSJaZ9NMwQ
      - STRIPE_PUBLIC_TEST_KEY=pk_test_51T6RXfHmiu72yDni4GPUfHAA8quzqXPZX5JRP6M0JWEgK3I7fekmDwyI0LMgl92L8uuw1K6hLBUIRilwrLSg78hJ00b7fUTLwM
      - STRIPE_SECRET_TEST_KEY=sk_test_51T6RXfHmiu72yDni7Gm25PuBX2Dh7IhEIyrbnDDZXUYvVnz8hgeylmVPAV3nPFux8ULGqPqBySCcmHMVWee9cAtH00ws2YDI4Q
